export const SET_COLLECTION = 'SET_COLLECTION'
export const SET_WISHLIST = 'SET_WISHLIST'
export const SET_ALBUM = 'SET_ALBUM'
export const SET_WISHLIST_ALBUM = 'SET_WISHLIST_ALBUM'
export const CLEAR_ALBUM = 'CLEAR_ALBUM'
export const CLEAR_WISHLIST_ALBUM = 'CLEAR_WISHLIST_ALBUM'

export const SET_MARK_FOR_DELETE = 'SET_MARK_FOR_DELETE'
